apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: shop
data:
  DB_SERVER: shopsqlsrvshouqds.privatelink.database.windows.net
  DB_NAME: shopdb
  CORS_ORIGIN: https://app.172.188.208.233.nip.io
  DB_ENCRYPT: "true"
  DB_TRUST_SERVER_CERTIFICATE: "false"