apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: acr-pull
      containers:
        - name: frontend
          image: shopshouqds.azurecr.io/frontend:v5
          ports:
            - containerPort: 80